version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/var/www/html
    ports:
      - 8800:8000

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: bst_api
      MYSQL_USER: bookstars
      MYSQL_PASSWORD: secretbst
      MYSQL_ROOT_PASSWORD: secretbst
  adminer:
    image: adminer
    ports:
      - 8080:8080
