name: 'Dev Deployment'

on:
  push:
    branches: [ development ]

jobs:
  bookstars-stageing-api-tests:

    runs-on: self-hosted

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3

    - name: "Setup nova authentication"
      run: |
          composer config http-basic.nova.laravel.com ${{ secrets.NOVA_USERNAME }} ${{ secrets.NOVA_PASSWORD }}
    
    - name: "Install app dependencies"
      run: composer install --ignore-platform-reqs

    - name: "Setup env file"
      env:
        APP_KEY: ${{ secrets.APP_KEY }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"

    - run: php artisan config:cache
    - run: php artisan route:cache
      