name: Integration

on:
  pull_request:
    branches: [ development ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    # - run: composer install
    - run: cp .env.example .env
    # - run: php artisan key:generate
    # - run: php artisan test